### PR TITLE
Add new editors' bios for Volume IV

### PR DESCRIPTION
**Pull request by cmrRose**

### CODE REVIEW

**Comment by mapsam** [comment]
This is the best pull request ever. Thanks @cmrRose! Will be good to write up a new blog post at some point to announce you all.

**Comment by ginmason** [comment]
Hi.  My bio has changed.  can you please advise me on how to make this change myself (I'm not git-hub saavy) or make the following please?  +<strong>Ginny Mason</strong> was the Assistant Editor for the third volume of the <em>Atlas of Design</em> and is a former cartographer and graphics editor at National Geographic Magazine. She is now Senior Cartographer at S&P Global Platts.  She likes maps that help people make informed decisions. You can follow her on Twitter at <a href="https://twitter.com/masonginny" target="_blank">@masonginny</a>.

**Comment by pinakographos** [comment]
One potentially-useful approach: future-proof the bio section by making it broader. Tim & I wrote ours so that they mostly won't need updating, even as we move around in our careers:

> Daniel Huffman served as Editor for the first two volumes of the Atlas. Working alongside founder Tim Wallace, he helped develop the template for the project, and is enormously proud of what their initial ideas have become. A high point of his life was seeing his name listed in a library catalogue. You can find him at somethingaboutmaps.com, or on Twitter at @pinakographos.
> 
> Tim Wallace was the first Editor of the Atlas of Design, serving from 2010–2013 and carrying the project from an initial idea to a beautiful finished volume. Though he is no longer involved in the project, our work today is still very much built upon his efforts, and the Atlas of Design remains enriched by the results of his hard work and vision. You can find him at timwallace.info, or on Twitter at @wallacetim.

**Comment by cmrRose** [comment]
Since Sam hasn't made those changes, I will assume that I'm in charge of
making website updates now... Ginny, I have now updated your bio on the AoD
website.

If you want to be able to make changes to the website in the future, we
could add your Github account as a contributor.

Caroline

**Comment by ginmason** [comment]
Thanks Caroline,
I don't see a need for me to make changes to that website on a regular
basis moving forward.
Thanks,
Ginny

**Comment by mapsam** [comment]
Thanks @cmrRose! Super helpful to have you running things here.

**Pull request merged**
